config/routes.rb
Sento::Kanban::Engine.routes.draw do
  resources :boards do
    resources :columns do
      member do
        get :delete
      end
      resources :cards, only: [:new, :create]
    end
    resources :cards, only: :update
    resources :users do
      post :add
    end
    resources :filters
  end
  resources :cards, except: [:index, :new, :create, :edit] do
    resources :comments
    resources :watchers
    resources :assignees
    member do
      get :edit_title, path: 'edit/title'
      get :edit_description, path: 'edit/description'
      patch :archive
    end
  end

  resources :users do
    collection do
      get 'ask-username', to: 'users#ask_username'
      get 'check-username', to: 'users#check_username'
      get :invite
    end
  end

  resource :search do
    collection do
      get :autocomplete
    end
  end

  resource :menu

  root to: 'boards#index'
end

app/controllers/sento/kanban/application_controller.rb
require_dependency 'sento/kanban/concerns/service_downtime_handling_for_elasticsearch'

module Sento
  module Kanban
    class ApplicationController < ActionController::Base
      protect_from_forgery with: :exception

      before_action :authenticate_user!, if: :using_devise?
      before_action :ensure_user_has_a_username

      after_action :prepare_unobtrusive_flash

      include Sento::Kanban::ServiceDowntimeHandlingForElasticSearch

      def kanban_source
        Sento::Kanban.using_devise ? current_user.boards : Sento::Kanban::Board
      end
      helper_method :kanban_source

      private

      #
      # This method creates the @ask_username variable which is used later in
      # order to show the modal asking the user to choose a username in the case
      # the current_user doesn't have one.
      #
      def ensure_user_has_a_username
        @ask_username = current_user.username.blank?
      end

      def create_and_assing_open_card
        @open_card = session[:open_card]
        session.delete(:open_card)
      end

      # TODO : Refactor this method
      def build_flash_message(type, options = {})
        final_action_name = action_name.dup
        final_resource_name = i18n_resource_name

        if options.present?
          final_resource_name = options.keys.first.to_s
          key = options.values.first
        else
          final_action_name << 'e' unless final_action_name.ends_with?('e')

          key = if type == :success
                  "#{final_action_name}d_object"
                else
                  "not_#{final_action_name}d_object"
                end
        end

        flash[type] = t("sento.kanban.messages.#{key}",
                        name: final_resource_name)
      end

      def using_devise?
        Sento::Kanban.using_devise == true
      end
    end
  end
end

app/controllers/sento/kanban/assignees_controller.rb
module Sento
  module Kanban
    class AssigneesController < ApplicationController
      before_action :fetches_current_card
      before_action :fetches_assignee, only: [:create, :edit, :destroy]
      before_action :fetches_all_members

      # GET /cards/1/assignees
      def index
        render layout: false
      end

      # POST /cards/1/assignees
      def create
        AssignCard.call(card: @card, user: @member, author: current_user)
      end

      # GET /cards/1/assignees/1/edit
      def edit
        render layout: false
      end

      # DELETE /cards/1/assignee/1
      def destroy
        UnassignCard.call(card: @card, user: @member, author: current_user)
        render :create
      end

      private

      def fetches_current_card
        # TODO : Handle the case where not using Devise
        @card = current_user.cards.includes(:assignees).find(params[:card_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, card: :not_found)
        redirect_to board_url(root_path)
      end

      def fetches_assignee
        id = params[:id]
        id = params[:assignee][:member_id] if params.key?(:assignee)
        @member = @card.board.all_members.find(id)
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, card: :not_found)
        redirect_to board_url(@card.board)
      end

      def fetches_all_members
        @members = @card.board.all_members.order(:username)
      end

      def i18n_resource_name
        t('sento.kanban.assignee')
      end
    end
  end
end

app/controllers/sento/kanban/boards_controller.rb
module Sento
  module Kanban
    class BoardsController < Sento::Kanban::ApplicationController
      before_action :set_board, only: [:show, :edit, :update, :destroy]
      before_action :fetches_all_boards, only: :index
      before_action :initialize_opening_card_if_needed, only: :show
      before_action :update_current_user_current_board
      before_action :detect_elasticsearch_service_downtime

      respond_to :html, :json

      # GET /boards
      def index; end

      # GET /boards/1
      def show
        respond_to do |format|
          format.html
          format.js { @columns = @board.columns }
        end
      end

      # GET /boards/new
      def new
        @board = Board.new
        respond_modal_with @board
      end

      # GET /boards/1/edit
      def edit
        respond_modal_with @board
      end

      # POST /boards
      def create
        @board = Board.new(board_params)
        if @board.save
          CreateNewBoard.call(author: current_user, board: @board)
          fetches_all_boards
        else
          build_flash_message(:error)
        end
        render :new
      end

      # PATCH/PUT /boards/1
      def update
        build_flash_message(@board.update(board_params) ? :success : :error)
        render :update
      end

      # DELETE /boards/1
      def destroy
        @board.destroy
        build_flash_message(:success)
        redirect_to boards_url
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_board
        @board = kanban_source.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, board: :not_found)
        redirect_to action: :index
      end

      # Only allow a trusted parameter "white list" through.
      def board_params
        params.require(:board).permit(:title, :description)
      end

      def fetches_all_boards
        @boards = kanban_source.all
      end

      #
      # In the case the user uses a card direct link, the application has
      # redirected him to this BoardsController and we will open the card.
      # This method sets the @open_card variable (which will trigger the click
      # on the card), and removes the `:open_card` from the user's session.
      #
      def initialize_opening_card_if_needed
        return if request.format.html?
        return unless session[:open_card]

        create_and_assing_open_card
      end

      def update_current_user_current_board
        current_user.update(current_board: @board)
      end

      def detect_elasticsearch_service_downtime
        Searchkick.server_version

        @elasticsearch_down = nil
      rescue Faraday::ConnectionFailed => exception
        Rails.logger.error 'ElasticSearch connection error: ' \
                           "#{exception.message}"
        @elasticsearch_down = true
        nil
      end

      def i18n_resource_name
        t('sento.kanban.board')
      end
    end
  end
end

app/controllers/sento/kanban/cards_controller.rb
module Sento
  module Kanban
    class CardsController < ApplicationController
      before_action :fetches_current_board
      before_action :fetches_current_column
      before_action :build_new_card, only: [:new, :create]
      before_action :set_card, only: [:show, :edit_title, :edit_description,
                                      :update, :destroy, :archive]
      before_action :redirect_to_the_board_with_direct_card_links
      before_action :build_new_comment, only: :show

      respond_to :html, :json

      # GET /boards/1/columns/1/cards
      # GET /boards/1/cards
      def index; end

      # GET /boards/1/columns/1/cards/1
      # GET /boards/1/cards/1
      # GET /cards/1
      def show
        respond_modal_with @card
      end

      # GET /boards/1/columns/1/cards/new
      # GET /boards/1/cards/new
      def new; end

      # GET /boards/1/columns/1/cards/1/edit/description
      # GET /boards/1/cards/1/edit/description
      # GET /cards/1/edit/description
      def edit_description; end

      # GET /boards/1/columns/1/cards/1/edit/title
      # GET /boards/1/cards/1/edit/title
      # GET /cards/1/edit/title
      def edit_title; end

      # POST /boards/1/columns/1/cards
      # POST /boards/1/cards
      def create
        if @new_card.save
          CreateNewCardCreatedActivity.call(board: @board, column: @column,
                                            card: @new_card,
                                            author: current_user)
        else
          build_flash_message(:error)
        end
        render :create
      end

      # PATCH/PUT /boards/1/columns/1/cards/1
      # PATCH/PUT /boards/1/cards/1
      # PATCH/PUT /cards/1
      def update
        if will_rename_the_card?
          RenameCard.call(card: @card, params: card_params,
                          author: current_user)
        end

        if will_update_the_card_description?
          ChangeCardDescription.call(card: @card, params: card_params,
                                     author: current_user)
        end

        if will_move_the_card?
          MoveCard.call(card: @card, params: card_params, author: current_user)
        end

        render :update
      end

      # DELETE /boards/1/columns/1/cards/1
      # DELETE /boards/1/cards/1
      # DELETE /cards/1
      def destroy
        @card.destroy
        build_flash_message(:success)
        redirect_to board_path(@board)
      end

      # PATCH /boards/1/cards/1/archive
      # PATCH /cards/1/archive
      def archive
        ArchiveCard.call(board: @board, card: @card, author: current_user)
        render :archive
      end

      private

      def fetches_current_board
        return unless params.key?(:board_id)

        @board = current_user.boards.find(params[:board_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, board: :not_found)
        redirect_to root_path
      end

      def fetches_current_column
        return unless params.key?(:column_id)

        @column = @board.columns.find(params[:column_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, column: :not_found)
        redirect_to board_path(@board)
      end

      def cards_source
        @column || @board || current_user
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_card
        @card = cards_source.cards.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, card: :not_found)
        redirect_to @board ? board_path(@board) : root_path
      end

      def build_new_card
        @new_card = cards_source.cards.new(card_params)
      end

      def build_new_comment
        @new_comment = @card.comments.new
      end

      # Only allow a trusted parameter "white list" through.
      def card_params
        return {} unless params.key?(:card)

        params.require(:card).permit(:title, :description, :card_order_position,
                                     :column_id)
      end

      def will_rename_the_card?
        return false unless card_params.key?(:title)

        @card.title != card_params[:title]
      end

      def will_update_the_card_description?
        return false unless card_params.key?(:description)

        @card.description != card_params[:description]
      end

      def will_move_the_card?
        return false unless card_params.key?(:column_id)

        @card.column_id != card_params[:column_id].to_i
      end

      def redirect_to_the_board_with_direct_card_links
        return true unless request.format.html?

        session[:open_card] = @card.id
        redirect_to board_path(@card.board)
      end

      def i18n_resource_name
        t('sento.kanban.card')
      end
    end
  end
end

app/controllers/sento/kanban/columns_controller.rb
module Sento
  module Kanban
    class ColumnsController < ApplicationController
      before_action :fetches_current_board
      before_action :build_new_column, only: [:new, :create]
      before_action :set_column, only: [:show, :edit, :update, :delete,
                                        :destroy]
      respond_to :html, :json

      # GET /boards/1/columns
      def index; end

      # GET /boards/1/columns/1
      def show; end

      # GET /boards/1/columns/new
      def new; end

      # GET /boards/1/columns/1/edit
      def edit; end

      # POST /boards/1/columns
      def create
        @new_column.position = @board.columns.count
        return unless @new_column.save
        CreateNewColumnCreatedActivity.call(board: @board, column: @new_column,
                                            author: current_user)
      end

      # PATCH/PUT /boards/1/columns/1
      def update
        build_flash_message(:error) unless @column.update(column_params)
        render :update
      end

      # GET /boards/1/columns/1/delete
      def delete
        respond_modal_with @column
      end

      # DELETE /boards/1/columns/1
      def destroy
        @column.destroy
        build_flash_message(:success)
        redirect_to board_url(@board)
      end

      private

      def fetches_current_board
        @board = current_user.boards.find(params[:board_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, board: :not_found)
        redirect_to root_url
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_column
        @column = @board.columns.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, column: :not_found)
        redirect_to action: :index
      end

      def column_params
        return {} unless params.key?(:column)

        params[:column].permit(:name)
      end

      def build_new_column
        @new_column = @board.columns.new(column_params)
      end

      def i18n_resource_name
        t('sento.kanban.column')
      end
    end
  end
end

app/controllers/sento/kanban/comments_controller.rb
module Sento
  module Kanban
    class CommentsController < ApplicationController
      before_action :fetches_current_board
      before_action :fetches_current_card
      before_action :set_comment, only: [:edit, :update, :destroy]

      # GET /boards/1/cards/1/comments/1/edit
      def edit; end

      # POST /boards/1/cards/1/comments
      def create
        context = CreateNewComment.call(card: @card, author: current_user,
                                        params: comment_params)
        @new_comment = context.comment

        build_flash_message(:error) if context.failure?

        render :create
      end

      # PATCH/PUT /boards/1/cards/1/comments/1
      def update
        build_flash_message(:error) unless @comment.update(comment_params)
        render :update
      end

      # DELETE /boards/1/cards/1/comments/1
      def destroy
        @comment.destroy
        build_flash_message(:success)

        respond_to do |format|
          format.html { redirect_to board_path(@board || @card.board) }
          format.js
        end
      end

      private

      def fetches_current_board
        return unless params.key?(:board_id)

        @board = current_user.boards.find(params[:board_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, board: :not_found)
        redirect_to root_url
      end

      def cards_source
        @board || current_user
      end

      def fetches_current_card
        @card = cards_source.cards.find(params[:card_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, card: :not_found)
        redirect_to board_url(@board)
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_comment
        @comment = @card.comments.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, comment: :not_found)
        redirect_to board_url(@board)
      end

      # Only allow a trusted parameter "white list" through.
      def comment_params
        return {} unless params.key?(:comment)

        params.require(:comment).permit(:body)
      end

      def i18n_resource_name
        t('sento.kanban.comment')
      end
    end
  end
end

app/controllers/sento/kanban/concerns/service_downtime_handling_for_elasticsearch.rb
module Sento
  module Kanban
    module ServiceDowntimeHandlingForElasticSearch
      extend ActiveSupport::Concern

      def render(*args)
        detect_elasticsearch_failure
        super
      end

      #
      # On create/update and destroy, ElasticSearch indexes are updated.
      # The model has a class attribute which will stores on error if
      # ElasticSearch is down or not and let continue the code which hides this
      # to the user.
      # Here we are then collecting this information in order to disable the
      # features using ElasticSearch.
      # As soon as ElasticSearch is back, the features are usable again.
      #
      def detect_elasticsearch_failure
        @elasticsearch_down ||= User.elasticsearch_down
      end
    end
  end
end

app/controllers/sento/kanban/filters_controller.rb
module Sento
  module Kanban
    class FiltersController < ApplicationController
      # GET /boards/1/filters
      def index; end
    end
  end
end

app/views/sento/kanban/boards/_all_members.html.slim
.row
  .col-xs-12
    .media
      .media-left
        = octicon 'organization', height: 25, class: 'icon'
      .media-body
        p.small-title= t('.all_members')
.row
  .col-xs-12
    #board-members.mb-1
      - unless menu_source.blank?
        - menu_source.members.each do |member|
          - present(member) do |presented_member|
            = link_to user_path(member) do
              = presented_member.avatar_url_or_fallback

.row
  .col-xs-12
    .media
      .media-left
        = octicon 'organization', height: 25, class: 'icon'
      .media-body
        p.small-title= t('.all_invited_members')
.row
  .col-xs-12
    #board-members.mb-1
      - unless menu_source.blank?
        - menu_source.virtual_members.each do |virtual_member|
          - present(virtual_member) do |presented_virtual_member|
            = link_to user_path(virtual_member) do
              = presented_virtual_member.avatar_url_or_fallback

app/views/sento/kanban/boards/_board_columns.html.slim
.sento-kanban.pt-1.pb-1 data-behavior="scrollable"
  - Array(@columns).each do |column|
    = render partial: 'sento/kanban/columns/column', locals: { column: column }
  
  .sento-kanban-container
    = link_to new_board_column_path(@board), remote: true, data: { purpose: 'new-column' } do
      .sento-kanban-column.new.center-block-flex
        p= t('.click_to_create')

app/views/sento/kanban/boards/_board_list.html.slim
- @boards.each do |board|
  = link_to board_path(board) do
    .card.mr-1
      .card-block
        h4.card-title= board.title
        h6.card-subtitle.text-muted= board.description

= link_to new_board_path, data: { modal: true, purpose: 'new-board' } do
  .card.mr-1.new-card
    .card-block.center-block-flex
      = octicon 'plus', height: 55
      p.text-xs-center.action-description.m-0= t('.new_board')

app/views/sento/kanban/boards/_form.html.slim
= simple_form_for(board, html: { class: 'form-horizontal' }) do |f|
  - if board.errors.any?
    #error_explanation
      h2
        = pluralize(board.errors.count, 'error')
        |   prohibited this board from being saved:

      ul
      - board.errors.full_messages.each do |message|
        li= message

  = f.input :title
  = f.input :description

  .modal-footer
    = f.button :submit, class: 'btn-primary'
    button type="button" class="btn btn-secondary" data-dismiss="modal"= t('sento.kanban.buttons.close')

app/views/sento/kanban/boards/_members.html.slim
- if menu_source.virtual_members.empty?
  .row
    .col-xs-12
      .media
        .media-left
          = octicon 'organization', height: 25, class: 'icon'
        .media-body
          p.small-title= t('.members')
  .row
    .col-xs-12
      #board-members.mb-1
        - unless menu_source.blank?
          - menu_source.members.each do |member|
            - present(member) do |presented_member|
              = link_to user_path(member) do
                = presented_member.avatar_url_or_fallback
- else
  .row
    .col-xs-6
      .media
        .media-left
          = octicon 'organization', height: 25, class: 'icon'
        .media-body
          p.small-title= t('.members')
    .col-xs-6
      .media
        .media-left
          = octicon 'organization', height: 25, class: 'icon'
        .media-body
          p.small-title= t('.invited_members')
  .row
    .col-xs-6
      #board-members.mb-1
        - unless menu_source.blank?
          - menu_source.members.each do |member|
            - present(member) do |presented_member|
              = link_to user_path(member) do
                = presented_member.avatar_url_or_fallback
    .col-xs-6
      #board-guests.mb-1
        - unless menu_source.blank?
          - menu_source.virtual_members.each do |virtual_member|
            - present(virtual_member) do |presented_virtual_member|
              = link_to user_path(virtual_member) do
                = presented_virtual_member.avatar_url_or_fallback

- if @board
  .row
    .col-xs-12.text-xs-center
      = link_to t('sento.kanban.buttons.add_member'), new_board_user_path(@board), class: 'btn btn-secondary', remote: true

app/views/sento/kanban/boards/edit.html.slim
= simple_form_for @board, remote: true, authenticity_token: true, html: { class: 'form-horizontal' } do |f|
  .modal-body
    h1= t('.title')
    
    fieldset.form-group
      legend= t('.details')
      = f.input :title
      = f.input :description

    fieldset.form-group
      legend.text-danger= t('.delete')
      .text-danger= t('.destroy_board_loose_data')
      br
      = link_to t('.confirm_delete', name: @board.title), board_path(@board), method: :delete, class: 'btn btn-danger'

  .modal-footer
    button type="button" class="btn btn-secondary ml-1" data-dismiss="modal"= t('sento.kanban.buttons.close')
    = f.button :submit, class: 'btn-primary ml-1'

app/views/sento/kanban/boards/index.html.slim
= content_for :title, t('.title')

.unobtrusive-flash-container

.container
  .row
    .col-md-12
      p#notice= notice

  .row
    .col-md-12
      h1= t('.title')

  .row
    .col-xs-12
      #boards-list
        h5.loading= t('sento.kanban.loading')

app/views/sento/kanban/boards/index.js.erb
$('#boards-list').html('<%= j render(partial: "board_list") %>');

app/views/sento/kanban/boards/new.html.slim
= simple_form_for @board, remote: true, authenticity_token: true, html: { class: 'form-horizontal' } do |f|
  .modal-body
    h1= t('.title')

    - if @board.errors.any?
      #error_explanation
        h2
          = pluralize(@board.errors.count, 'error')
          |   prohibited this board from being saved:

        ul
        - @board.errors.full_messages.each do |message|
          li= message

    = f.input :title, input_html: { tabindex: 1 }
    = f.input :description, input_html: { tabindex: 2 }

  .modal-footer
    button type="button" class="btn btn-secondary ml-1" data-dismiss="modal"= t('sento.kanban.buttons.close')
    = f.button :submit, t('sento.kanban.buttons.create'), class: 'btn-primary ml-1'

javascript:
  selectFirstActiveInput();

app/views/sento/kanban/boards/new.js.erb
<% if @board.errors.empty? %>
  window.location.href = '<%= board_path(@board) %>';
<% else %>
  <% object_class_name = @board.class.name.demodulize.underscore %>
  <% @board.errors.each do |attribute, message| %>
    var field = $("#<%= object_class_name %>_<%= attribute %>"),
        formGroup = field.closest('div.form-group');
    // Removes previously created error messages
    formGroup.find('.form-control-feedback').remove();
    formGroup.addClass('has-danger');
    field.addClass('form-control-danger');
    formGroup.append('<div class="form-control-feedback"><%= message %></div>');
  <% end %>
<% end %>

app/views/sento/kanban/boards/show.html.slim
= content_for :title, @board.title

#board-content
  h5.loading= t('sento.kanban.loading')

app/views/sento/kanban/boards/show.js.erb
// Page content
$('#board-content').html('<%= j render(partial: "board_columns") %>');

applyDragula();

<% if @open_card && @ask_username == false %>
  $('.sento-kanban-cards a.card-action-link[data-card-id="<%= @open_card %>"]').trigger('click');
<% end %>

app/views/sento/kanban/boards/update.js.erb
<% if @board.errors.empty? %>
  $('#mainModal').modal('hide');
<% else %>
  <% object_class_name = @board.class.name.demodulize.underscore %>
  <% @board.errors.each do |attribute, message| %>
    var field = $("#<%= object_class_name %>_<%= attribute %>"),
        formGroup = field.closest('div.form-group'),
        columnBody = formGroup.closest('.sento-kanban-column').find('.sento-kanban-column-body');
    // Removes previously created error messages
    formGroup.find('.form-control-feedback').remove();
    columnBody.removeClass('mt-2');
    $('input[type="text"].form-control-danger').removeClass('form-control-danger');

    // Adds the field error
    formGroup.addClass('has-danger');
    field.addClass('form-control-danger');
    formGroup.append('<div class="form-control-feedback mt-0"><%= @column.errors.full_message(attribute, message) %></div>');
    columnBody.addClass('mt-2');
  <% end %>
<% end %>