config/routes.rb
Sento::Kanban::Engine.routes.draw do
  resources :boards do
    resources :columns do
      member do
        get :delete
      end
      resources :cards, only: [:new, :create]
    end
    resources :cards, only: :update
    resources :users do
      post :add
    end
    resources :filters
  end
  resources :cards, except: [:index, :new, :create, :edit] do
    resources :comments
    resources :watchers
    resources :assignees
    member do
      get :edit_title, path: 'edit/title'
      get :edit_description, path: 'edit/description'
      patch :archive
    end
  end

  resources :users do
    collection do
      get 'ask-username', to: 'users#ask_username'
      get 'check-username', to: 'users#check_username'
      get :invite
    end
  end

  resource :search do
    collection do
      get :autocomplete
    end
  end

  resource :menu

  root to: 'boards#index'
end

app/controllers/sento/kanban/application_controller.rb
require_dependency 'sento/kanban/concerns/service_downtime_handling_for_elasticsearch'

module Sento
  module Kanban
    class ApplicationController < ActionController::Base
      protect_from_forgery with: :exception

      before_action :authenticate_user!, if: :using_devise?
      before_action :ensure_user_has_a_username

      after_action :prepare_unobtrusive_flash

      include Sento::Kanban::ServiceDowntimeHandlingForElasticSearch

      def kanban_source
        Sento::Kanban.using_devise ? current_user.boards : Sento::Kanban::Board
      end
      helper_method :kanban_source

      private

      #
      # This method creates the @ask_username variable which is used later in
      # order to show the modal asking the user to choose a username in the case
      # the current_user doesn't have one.
      #
      def ensure_user_has_a_username
        @ask_username = current_user.username.blank?
      end

      def create_and_assing_open_card
        @open_card = session[:open_card]
        session.delete(:open_card)
      end

      # TODO : Refactor this method
      def build_flash_message(type, options = {})
        final_action_name = action_name.dup
        final_resource_name = i18n_resource_name

        if options.present?
          final_resource_name = options.keys.first.to_s
          key = options.values.first
        else
          final_action_name << 'e' unless final_action_name.ends_with?('e')

          key = if type == :success
                  "#{final_action_name}d_object"
                else
                  "not_#{final_action_name}d_object"
                end
        end

        flash[type] = t("sento.kanban.messages.#{key}",
                        name: final_resource_name)
      end

      def using_devise?
        Sento::Kanban.using_devise == true
      end
    end
  end
end

app/controllers/sento/kanban/assignees_controller.rb
module Sento
  module Kanban
    class AssigneesController < ApplicationController
      before_action :fetches_current_card
      before_action :fetches_assignee, only: [:create, :edit, :destroy]
      before_action :fetches_all_members

      # GET /cards/1/assignees
      def index
        render layout: false
      end

      # POST /cards/1/assignees
      def create
        AssignCard.call(card: @card, user: @member, author: current_user)
      end

      # GET /cards/1/assignees/1/edit
      def edit
        render layout: false
      end

      # DELETE /cards/1/assignee/1
      def destroy
        UnassignCard.call(card: @card, user: @member, author: current_user)
        render :create
      end

      private

      def fetches_current_card
        # TODO : Handle the case where not using Devise
        @card = current_user.cards.includes(:assignees).find(params[:card_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, card: :not_found)
        redirect_to board_url(root_path)
      end

      def fetches_assignee
        id = params[:id]
        id = params[:assignee][:member_id] if params.key?(:assignee)
        @member = @card.board.all_members.find(id)
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, card: :not_found)
        redirect_to board_url(@card.board)
      end

      def fetches_all_members
        @members = @card.board.all_members.order(:username)
      end

      def i18n_resource_name
        t('sento.kanban.assignee')
      end
    end
  end
end

app/controllers/sento/kanban/boards_controller.rb
module Sento
  module Kanban
    class BoardsController < Sento::Kanban::ApplicationController
      before_action :set_board, only: [:show, :edit, :update, :destroy]
      before_action :fetches_all_boards, only: :index
      before_action :initialize_opening_card_if_needed, only: :show
      before_action :update_current_user_current_board
      before_action :detect_elasticsearch_service_downtime

      respond_to :html, :json

      # GET /boards
      def index; end

      # GET /boards/1
      def show
        respond_to do |format|
          format.html
          format.js { @columns = @board.columns }
        end
      end

      # GET /boards/new
      def new
        @board = Board.new
        respond_modal_with @board
      end

      # GET /boards/1/edit
      def edit
        respond_modal_with @board
      end

      # POST /boards
      def create
        @board = Board.new(board_params)
        if @board.save
          CreateNewBoard.call(author: current_user, board: @board)
          fetches_all_boards
        else
          build_flash_message(:error)
        end
        render :new
      end

      # PATCH/PUT /boards/1
      def update
        build_flash_message(@board.update(board_params) ? :success : :error)
        render :update
      end

      # DELETE /boards/1
      def destroy
        @board.destroy
        build_flash_message(:success)
        redirect_to boards_url
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_board
        @board = kanban_source.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, board: :not_found)
        redirect_to action: :index
      end

      # Only allow a trusted parameter "white list" through.
      def board_params
        params.require(:board).permit(:title, :description)
      end

      def fetches_all_boards
        @boards = kanban_source.all
      end

      #
      # In the case the user uses a card direct link, the application has
      # redirected him to this BoardsController and we will open the card.
      # This method sets the @open_card variable (which will trigger the click
      # on the card), and removes the `:open_card` from the user's session.
      #
      def initialize_opening_card_if_needed
        return if request.format.html?
        return unless session[:open_card]

        create_and_assing_open_card
      end

      def update_current_user_current_board
        current_user.update(current_board: @board)
      end

      def detect_elasticsearch_service_downtime
        Searchkick.server_version

        @elasticsearch_down = nil
      rescue Faraday::ConnectionFailed => exception
        Rails.logger.error 'ElasticSearch connection error: ' \
                           "#{exception.message}"
        @elasticsearch_down = true
        nil
      end

      def i18n_resource_name
        t('sento.kanban.board')
      end
    end
  end
end

app/controllers/sento/kanban/cards_controller.rb
module Sento
  module Kanban
    class CardsController < ApplicationController
      before_action :fetches_current_board
      before_action :fetches_current_column
      before_action :build_new_card, only: [:new, :create]
      before_action :set_card, only: [:show, :edit_title, :edit_description,
                                      :update, :destroy, :archive]
      before_action :redirect_to_the_board_with_direct_card_links
      before_action :build_new_comment, only: :show

      respond_to :html, :json

      # GET /boards/1/columns/1/cards
      # GET /boards/1/cards
      def index; end

      # GET /boards/1/columns/1/cards/1
      # GET /boards/1/cards/1
      # GET /cards/1
      def show
        respond_modal_with @card
      end

      # GET /boards/1/columns/1/cards/new
      # GET /boards/1/cards/new
      def new; end

      # GET /boards/1/columns/1/cards/1/edit/description
      # GET /boards/1/cards/1/edit/description
      # GET /cards/1/edit/description
      def edit_description; end

      # GET /boards/1/columns/1/cards/1/edit/title
      # GET /boards/1/cards/1/edit/title
      # GET /cards/1/edit/title
      def edit_title; end

      # POST /boards/1/columns/1/cards
      # POST /boards/1/cards
      def create
        if @new_card.save
          CreateNewCardCreatedActivity.call(board: @board, column: @column,
                                            card: @new_card,
                                            author: current_user)
        else
          build_flash_message(:error)
        end
        render :create
      end

      # PATCH/PUT /boards/1/columns/1/cards/1
      # PATCH/PUT /boards/1/cards/1
      # PATCH/PUT /cards/1
      def update
        if will_rename_the_card?
          RenameCard.call(card: @card, params: card_params,
                          author: current_user)
        end

        if will_update_the_card_description?
          ChangeCardDescription.call(card: @card, params: card_params,
                                     author: current_user)
        end

        if will_move_the_card?
          MoveCard.call(card: @card, params: card_params, author: current_user)
        end

        render :update
      end

      # DELETE /boards/1/columns/1/cards/1
      # DELETE /boards/1/cards/1
      # DELETE /cards/1
      def destroy
        @card.destroy
        build_flash_message(:success)
        redirect_to board_path(@board)
      end

      # PATCH /boards/1/cards/1/archive
      # PATCH /cards/1/archive
      def archive
        ArchiveCard.call(board: @board, card: @card, author: current_user)
        render :archive
      end

      private

      def fetches_current_board
        return unless params.key?(:board_id)

        @board = current_user.boards.find(params[:board_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, board: :not_found)
        redirect_to root_path
      end

      def fetches_current_column
        return unless params.key?(:column_id)

        @column = @board.columns.find(params[:column_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, column: :not_found)
        redirect_to board_path(@board)
      end

      def cards_source
        @column || @board || current_user
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_card
        @card = cards_source.cards.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, card: :not_found)
        redirect_to @board ? board_path(@board) : root_path
      end

      def build_new_card
        @new_card = cards_source.cards.new(card_params)
      end

      def build_new_comment
        @new_comment = @card.comments.new
      end

      # Only allow a trusted parameter "white list" through.
      def card_params
        return {} unless params.key?(:card)

        params.require(:card).permit(:title, :description, :card_order_position,
                                     :column_id)
      end

      def will_rename_the_card?
        return false unless card_params.key?(:title)

        @card.title != card_params[:title]
      end

      def will_update_the_card_description?
        return false unless card_params.key?(:description)

        @card.description != card_params[:description]
      end

      def will_move_the_card?
        return false unless card_params.key?(:column_id)

        @card.column_id != card_params[:column_id].to_i
      end

      def redirect_to_the_board_with_direct_card_links
        return true unless request.format.html?

        session[:open_card] = @card.id
        redirect_to board_path(@card.board)
      end

      def i18n_resource_name
        t('sento.kanban.card')
      end
    end
  end
end

app/controllers/sento/kanban/columns_controller.rb
module Sento
  module Kanban
    class ColumnsController < ApplicationController
      before_action :fetches_current_board
      before_action :build_new_column, only: [:new, :create]
      before_action :set_column, only: [:show, :edit, :update, :delete,
                                        :destroy]
      respond_to :html, :json

      # GET /boards/1/columns
      def index; end

      # GET /boards/1/columns/1
      def show; end

      # GET /boards/1/columns/new
      def new; end

      # GET /boards/1/columns/1/edit
      def edit; end

      # POST /boards/1/columns
      def create
        @new_column.position = @board.columns.count
        return unless @new_column.save
        CreateNewColumnCreatedActivity.call(board: @board, column: @new_column,
                                            author: current_user)
      end

      # PATCH/PUT /boards/1/columns/1
      def update
        build_flash_message(:error) unless @column.update(column_params)
        render :update
      end

      # GET /boards/1/columns/1/delete
      def delete
        respond_modal_with @column
      end

      # DELETE /boards/1/columns/1
      def destroy
        @column.destroy
        build_flash_message(:success)
        redirect_to board_url(@board)
      end

      private

      def fetches_current_board
        @board = current_user.boards.find(params[:board_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, board: :not_found)
        redirect_to root_url
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_column
        @column = @board.columns.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, column: :not_found)
        redirect_to action: :index
      end

      def column_params
        return {} unless params.key?(:column)

        params[:column].permit(:name)
      end

      def build_new_column
        @new_column = @board.columns.new(column_params)
      end

      def i18n_resource_name
        t('sento.kanban.column')
      end
    end
  end
end

app/controllers/sento/kanban/comments_controller.rb
module Sento
  module Kanban
    class CommentsController < ApplicationController
      before_action :fetches_current_board
      before_action :fetches_current_card
      before_action :set_comment, only: [:edit, :update, :destroy]

      # GET /boards/1/cards/1/comments/1/edit
      def edit; end

      # POST /boards/1/cards/1/comments
      def create
        context = CreateNewComment.call(card: @card, author: current_user,
                                        params: comment_params)
        @new_comment = context.comment

        build_flash_message(:error) if context.failure?

        render :create
      end

      # PATCH/PUT /boards/1/cards/1/comments/1
      def update
        build_flash_message(:error) unless @comment.update(comment_params)
        render :update
      end

      # DELETE /boards/1/cards/1/comments/1
      def destroy
        @comment.destroy
        build_flash_message(:success)

        respond_to do |format|
          format.html { redirect_to board_path(@board || @card.board) }
          format.js
        end
      end

      private

      def fetches_current_board
        return unless params.key?(:board_id)

        @board = current_user.boards.find(params[:board_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, board: :not_found)
        redirect_to root_url
      end

      def cards_source
        @board || current_user
      end

      def fetches_current_card
        @card = cards_source.cards.find(params[:card_id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, card: :not_found)
        redirect_to board_url(@board)
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_comment
        @comment = @card.comments.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        build_flash_message(:error, comment: :not_found)
        redirect_to board_url(@board)
      end

      # Only allow a trusted parameter "white list" through.
      def comment_params
        return {} unless params.key?(:comment)

        params.require(:comment).permit(:body)
      end

      def i18n_resource_name
        t('sento.kanban.comment')
      end
    end
  end
end

app/controllers/sento/kanban/concerns/service_downtime_handling_for_elasticsearch.rb
module Sento
  module Kanban
    module ServiceDowntimeHandlingForElasticSearch
      extend ActiveSupport::Concern

      def render(*args)
        detect_elasticsearch_failure
        super
      end

      #
      # On create/update and destroy, ElasticSearch indexes are updated.
      # The model has a class attribute which will stores on error if
      # ElasticSearch is down or not and let continue the code which hides this
      # to the user.
      # Here we are then collecting this information in order to disable the
      # features using ElasticSearch.
      # As soon as ElasticSearch is back, the features are usable again.
      #
      def detect_elasticsearch_failure
        @elasticsearch_down ||= User.elasticsearch_down
      end
    end
  end
end

app/controllers/sento/kanban/filters_controller.rb
module Sento
  module Kanban
    class FiltersController < ApplicationController
      # GET /boards/1/filters
      def index; end
    end
  end
end

app/views/sento/kanban/cards/_card.html.slim
= link_to card_path(card), class: 'card-action-link', data: { modal: true, card_id: card.id } do
  .card.card-block
    p.card-title= card.title

app/views/sento/kanban/cards/_card_assignees.html.slim
- if @card.assignees.present?
  .card-members.mt-1
    h3.card-members-header= t('sento.kanban.assignee').pluralize.capitalize
    - @card.assignees.order(:username).each do |assignee|
      - present(assignee) do |presented_assignee|
        = link_to edit_card_assignee_path(@card, assignee), title: "#{presented_assignee.fullname_or_username}<button type='button' class='close' aria-label='Close'><span aria-hidden='true'>&times;</span></button>", data: { toggle: 'popover', html: true, container: 'body', placement: 'bottom' } do
          = presented_assignee.avatar_url_or_fallback

app/views/sento/kanban/cards/_card_description_and_link.html.slim
- if @card.description.present?
  span= t('.description')
  '
  = link_to t('.edit'), edit_description_card_path(@card), remote: true
  br
  p= @card.description
- else
  = link_to edit_description_card_path(@card), remote: true do
    .media
      .media-left
        = octicon 'note', height: 23
      .media-body
        = t('.edit_description')

app/views/sento/kanban/cards/_card_description_edit.html.slim
= simple_form_for @card, method: :patch, remote: true, authenticity_token: true, html: { class: 'form-horizontal' } do |f|
  = f.input :description, label: false
  .form-group
    = f.submit t('sento.kanban.buttons.save'), class: 'btn btn-success mb-1'
    button.btn.btn-secondary.ml-1.mb-1 type="button" data-behavior="cancel-edit"= t('sento.kanban.buttons.cancel')

app/views/sento/kanban/cards/_card_title_edit.html.slim
= simple_form_for @card, method: :patch, remote: true, authenticity_token: true, html: { class: 'form-horizontal' } do |f|
  = f.input :title, label: false
  .form-group
    = f.submit t('sento.kanban.buttons.save'), class: 'btn btn-success mb-1'
    button.btn.btn-secondary.ml-1.mb-1 type="button" data-behavior="cancel-edit"= t('sento.kanban.buttons.cancel')

app/views/sento/kanban/cards/_card_watchers.html.slim
- if @card.watchers.present?
  .card-members.mt-1
    h3.card-members-header= t('sento.kanban.watcher').pluralize.capitalize
    - @card.watchers.order(:username).each do |watcher|
      - present(watcher) do |presented_watcher|
        = link_to edit_card_watcher_path(@card, watcher), title: "#{presented_watcher.fullname_or_username}<button type='button' class='close' aria-label='Close'><span aria-hidden='true'>&times;</span></button>", data: { toggle: 'popover', html: true, container: 'body', placement: 'bottom' } do
          = presented_watcher.avatar_url_or_fallback

app/views/sento/kanban/cards/_new_card.html.slim
.card.card-block.new.p-0
  = simple_form_for @new_card, url: board_column_cards_path(@board, @column), remote: true do |f|
    = f.input :card_order_position, as: :hidden, input_html: { value: 0 }
    = f.input :title, label: false, as: :text

app/views/sento/kanban/cards/archive.js.erb
$('#mainModal').modal('hide');
$('a[data-card-id="<%= @card.id %>"]').remove();

app/views/sento/kanban/cards/create.js.erb
<% if @new_card.errors.empty? %>
  var newCard = $('.sento-kanban-column[data-id="<%= @column.id %>"] .card.card-block.new');
  newCard.before('<%= j render(partial: "card", locals: { board: @board, column: @column, card: @new_card })%>');
  newCard.remove();
<% end %>

app/views/sento/kanban/cards/edit_description.js.erb
$('#card-description').html('<%= j render(partial: "card_description_edit") %>');

$('*[data-behavior="cancel-edit"]').on('click', function() {
  $('#card-description').html('<%= j render(partial: "card_description_and_link") %>');
});

selectFirstActiveInput();

$(document).keyup(function(event) {
  if (event.keyCode == 27) { // escape key
    $('#card-description').html('<%= j render(partial: "card_description_and_link") %>');
  }
});

app/views/sento/kanban/cards/edit_title.js.erb
$('#card-title').html('<%= j render(partial: "card_title_edit") %>');

var orginalTitleHtml = '<%= link_to edit_title_card_path(@card), class: "editable", remote: true do %><h4 class="modal-title"><%= j @card.title %></h4><% end %>';

$('*[data-behavior="cancel-edit"]').on('click', function() {
  $('#card-title').html(orginalTitleHtml);
});

$('#mainModal').on('hide.bs.modal', function(event) {
  if ($('form#edit_card_<%= @card.id %>').length > 0) {
    event.preventDefault();
    selectFirstActiveInput();
  }
});

selectFirstActiveInput();

$('form').keyup(function(event) {
  if (event.keyCode == 27) { // escape key
    $('#card-title').html(orginalTitleHtml);
  }
});

app/views/sento/kanban/cards/new.js.erb
var columnCardContainer = $('.sento-kanban-column[data-id="<%= @column.id %>"] .sento-kanban-cards');
columnCardContainer.prepend('<%= j render(partial: "new_card") %>');

$('form#new_card textarea#card_title').keyup(function(event) {
  if (event.keyCode == 13) { $('form#new_card').submit(); }
});

// Toggle the dropdown (the call to dropdown('toggle') as described in the
// documentation of Bootstrap makes the dropdown no more working)
$('.dropdown.open').trigger('click');

selectFirstActiveInput();

$(document).keyup(function(event) {
  if (event.keyCode == 27) { // escape key
    $('.card.card-block.new').remove();
  }
});

app/views/sento/kanban/cards/show.html.slim
- present(@card) do |card|
  .modal-body
    .container-fluid.pl-0
      .row
        .col-xs-12
          .media
            .media-left
              = octicon 'note', height: 35, class: 'icon'
            .media-body
              #card-title
                = link_to edit_title_card_path(@card), class: 'editable', remote: true do
                  h4.modal-title= card.title
              p
                | in list
                '
                strong= card.column_name

                - if Rails.env.development?
                  |  at position:
                  '
                  strong= card.card_order

      .row
        .col-xs-6.col-sm-9
          .row
            .col-xs-12
              #card-watchers.float-xs-left
                = render partial: 'card_watchers'
              #card-assignees.float-xs-left.pl-2
                = render partial: 'card_assignees'

          .row
            .col-xs-12
              #card-description
                = render partial: 'card_description_and_link'

          .row
            .col-xs-12
              .media
                .media-left
                  = octicon 'comment', height: 30, class: 'icon'
                .media-body
                  p.small-title= t('.comment_section_title')
          .row
            .col-xs-12
              .media
                .media-left
                  - present(current_user) do |user|
                    = user.avatar_url_or_fallback
                .media-body
                  = simple_form_for @new_comment, url: card_comments_path(@card), method: :post, remote: true do |f|
                    = f.input :body, label: false
                    .form-group
                      = f.submit t('sento.kanban.buttons.save'), class: 'btn btn-success mb-1'

          .row
            .col-xs-12
              .media
                .media-left
                  = octicon 'pulse', height: 30, class: 'icon'
                .media-body
                  p.small-title= t('.activity_section_title')
          .row
            .col-xs-12
              #card-activities
                = render partial: 'sento/kanban/shared/activities', locals: { object: card }

        .col-xs-6.col-sm-3
          p.small-title= t('.add_title')
          = link_to t('sento.kanban.buttons.watchers'), card_watchers_path(@card), class: 'btn btn-secondary btn-block', title: "#{t('sento.kanban.buttons.watchers')}<button type='button' class='close' aria-label='Close'><span aria-hidden='true'>&times;</span></button>", data: { toggle: 'popover', html: true, container: 'body', placement: 'bottom' }
          = link_to t('sento.kanban.buttons.assignees'), card_assignees_path(@card), class: 'btn btn-secondary btn-block', title: "#{t('sento.kanban.buttons.assignees')}<button type='button' class='close' aria-label='Close'><span aria-hidden='true'>&times;</span></button>", data: { toggle: 'popover', html: true, container: 'body', placement: 'bottom' }
          br
          p.small-title= t('.actions_title')
          = link_to t('sento.kanban.buttons.archive'), archive_card_path(@card), method: :patch, class: 'btn btn-warning btn-block', remote: true
          = link_to t('sento.kanban.buttons.delete'), card_path(@card), method: :delete, class: 'btn btn-danger btn-block'


  - present(@card.board) do |presented_board|
    javascript:
      window.history.pushState(null, "#{j card.page_title}", "#{card_path(@card)}");
      document.title = "#{j card.page_title}";

      $('#mainModal').on('hide.bs.modal', function(event) {
        window.history.pushState(null, "#{j presented_board.page_title}", "#{board_path(@card.board)}");
        document.title = "#{j presented_board.page_title}";
        $('*[data-toggle="popover"]').popover('hide');
      });
        
      applyBootstrapPopover();

app/views/sento/kanban/cards/update.js.erb
<% if @card.errors.empty? %>
  $('#card-title').html('<%= link_to edit_title_card_path(@card), class: "editable", remote: true do %><h4 class="modal-title"><%= j @card.title %></h4><% end %>');
  $('#card-description').html('<%= j render(partial: "card_description_and_link") %>');
  $('#card-activities').html('<%= j render(partial: "sento/kanban/shared/activities", locals: { object: @card }) %>');
<% else %>
  <% object_class_name = @card.class.name.demodulize.underscore %>
  <% @card.errors.each do |attribute, message| %>
    var field = $("#<%= object_class_name %>_<%= attribute %>"),
        formGroup = field.closest('div.form-group');

    // Removes previously created error messages
    formGroup.find('.form-control-feedback').remove();
    $('input[type="text"].form-control-danger').removeClass('form-control-danger');

    // Adds the field error
    formGroup.addClass('has-danger');
    field.addClass('form-control-danger');
    formGroup.append('<div class="form-control-feedback mt-0"><%= @card.errors.full_message(attribute, message) %></div>');
  <% end %>
<% end %>